/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}", "../../packages/core/src/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        background: 'rgba(var(--background), <alpha-value>)',
        card: 'rgba(var(--card), <alpha-value>)',
        primary: 'rgba(var(--primary), <alpha-value>)',
        foreground: 'rgba(var(--foreground), <alpha-value>)',
        'primary-foreground': 'rgba(var(--primary-foreground), <alpha-value>)',
        'light-primary': 'rgba(var(--light-primary), <alpha-value>)',
        'light-primary-foreground': 'rgba(var(--light-primary-foreground), <alpha-value>)',
        secondary: 'rgba(var(--secondary), <alpha-value>)',
        'secondary-foreground': 'rgba(var(--secondary-foreground), <alpha-value>)',
        accent: 'rgba(var(--accent), <alpha-value>)',
        'accent-foreground': 'rgba(var(--accent-foreground), <alpha-value>)',
        warning: 'rgba(var(--warning), <alpha-value>)',
        'warning-foreground': 'rgba(var(--warning-foreground), <alpha-value>)',
        success: 'rgba(var(--success), <alpha-value>)',
        'success-foreground': 'rgba(var(--success-foreground), <alpha-value>)',
        error: 'rgba(var(--error), <alpha-value>)',
        'error-foreground': 'rgba(var(--error-foreground), <alpha-value>)',
        destructive: 'rgba(var(--destructive), <alpha-value>)',
        'destructive-foreground': 'rgba(var(--destructive-foreground), <alpha-value>)',
        muted: 'rgba(var(--muted), <alpha-value>)',
        'muted-foreground': 'rgba(var(--muted-foreground), <alpha-value>)',
        border: 'rgba(var(--border), <alpha-value>)',
        divider: 'var(--divider)',
        shadow: 'var(--shadow)',
      },
      dropShadow: {
        'card': '0px 4px 6px rgba(0, 0, 0, 0.05)',
        'button': '0px 2px 4px rgba(0, 0, 0, 0.05)',
      },
      borderRadius: {
        radius: 'var(--radius)',
      },
      maxWidth: {
        'container-size': '1280px',
      },
    },
  },
  future: {
    hoverOnlyWhenSupported: true,
  },
  plugins: [
    ({ addBase }) => addBase({
      ":root": {
        "--background": "249, 249, 249",
        "--card": "255, 255, 255",
        "--primary": "101, 165, 240",
        "--foreground": "34, 34, 34",
        "--primary-foreground": "249, 249, 249",
        "--light-primary": "101, 165, 240",
        "--light-primary-foreground": "30, 123, 232",
        "--secondary": "224, 22, 123",
        "--secondary-foreground": "255, 255, 255",
        "--accent": "224, 22, 123",
        "--accent-foreground": "255, 255, 255",
        "--warning": "245, 166, 35",
        "--warning-foreground": "255, 255, 255",
        "--success": "46, 204, 113",
        "--success-foreground": "255, 255, 255",
        "--error": "255, 56, 96",
        "--error-foreground": "255, 255, 255",
        "--destructive": "212, 15, 54",
        "--destructive-foreground": "255, 255, 255",
        "--muted-foreground": "108, 117, 125",
        "--border": "217, 216, 216",
        "--muted": "240, 240, 240",
        "--radius": "0.65rem",
        "--shadow": "rgba(0, 0, 0, 0.05)",
        "--divider": "rgba(0, 0, 0, 0.12)",
      }
    })],
};

